### ISSUE TITLE
Multiple galleries 

### ISSUE THREAD

**Issue by michaelbeil** [AesopInteractive/lasso#80]
When adding more than one gallery, all galleries receive the last added gallery ID. 

It seems like our API is dynamically updating all galleries to be equal. However, all galleries are not equal.

``` javascript
// make an ajax call to deal with gallery saving or creating only if it's a gallery
if ( 'gallery' == cdata['componentType'] ) {

    var data = {
        action:         form.hasClass('creating-gallery') ? 'process_gallery_create' : 'process_gallery_update',
        postid:         lasso_editor.postid,
        unique:         cdata['unique'],
        fields:         cleanFields(cdata),
        gallery_type:   $('#ase_gallery_type').val(),
        gallery_ids:    $('#ase_gallery_ids').val(),
        nonce:          $('#lasso-generator-nonce').val()
    }
```

https://github.com/AesopInteractive/lasso/blob/master/public/assets/js/source/process-save-component.js#L39-L107

**Comment by zamoose** [comment]
Came here to post about the exact same thing. Add a second gallery, and it seems to nuke everything beyond said gallery.

**Comment by bearded-avenger** [comment]
seems to check out locally ^

**Comment by michaelbeil** [comment]
I tested release/0.9.5 and I cannot create a second gallery with Lasso from the front-end without needing to create a new gallery from the WordPress dashboard under ASE's gallery CPT.
![screen shot 2015-06-08 at 2 55 34 pm](https://cloud.githubusercontent.com/assets/4752949/8043942/e0038f40-0dee-11e5-81d9-f2c48d3d3bbf.png)

**Comment by bearded-avenger** [comment]
eh?

**Comment by bearded-avenger** [comment]
can you make a new issue? that's a bug in teh workflow I've been meaning to fix (it's separate than this postid cross contamination crud)

**Comment by michaelbeil** [comment]
Done.

**Comment by zamoose** [comment]
Michael:
I think this is the status quo? I had to do the same as well.

Also, using the Cover theme, all the text is the wrong color in the Lasso
fly-overs. I'm betting it's a bad CSS rule specific to the theme, but it's
still a problem.

On Mon, Jun 8, 2015 at 4:02 PM, Nick Haskins notifications@github.com
wrote:

> eh?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AesopInteractive/lasso/issues/80#issuecomment-110121498
> .

## 

-Doug

**Comment by bearded-avenger** [comment]
_makes note to pull down cover_

**Comment by michaelbeil** [comment]
@zamoose ~~> https://github.com/AesopInteractive/lasso/issues/86

re Cover: 
![screen shot 2015-06-08 at 3 08 54 pm](https://cloud.githubusercontent.com/assets/4752949/8044123/522b81d0-0df0-11e5-8ce7-0fc6f709473a.png)

Looks like Cover's styles are overwriting Lasso's sidebar styles:
![screen shot 2015-06-08 at 3 24 20 pm](https://cloud.githubusercontent.com/assets/4752949/8044475/82f7678c-0df2-11e5-8bb2-606406126b76.png)

**Comment by bearded-avenger** [comment]
lasso doesnt have any styles set which is why it's overriding. will fix.

**Comment by michaelbeil** [comment]
Aha.
